version: '3.9'

services:
  booking-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: booking-service-dev
    ports:
      - "3005:3005"
    environment:
      PORT: 3005
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_TTL: ${REDIS_TTL}
      KAFKA_BROKER: ${KAFKA_BROKER}
      KAFKA_CLIENT_ID: ${KAFKA_CLIENT_ID}
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npm run start:dev"
    networks:
      my_custom_network:
        ipv4_address: ${APP_IP}

networks:
  my_custom_network:
    external: true

